export TF_VAR_environment_namespace=dev
export TF_VAR_vpc_cidr_block=10.0.0.0/16
export TF_VAR_private_subnet_count=2
export TF_VAR_route53_zone_id=Z0968214C1Y55Z5CSGI9

INTENDED_ACCOUNT = 800344761765

include $(shell git rev-parse --show-toplevel)/ops/terraform.mk
