export TF_VAR_environment_namespace=prod
export TF_VAR_vpc_cidr_block=10.0.0.0/16
export TF_VAR_private_subnet_count=3
export TF_VAR_route53_zone_id=Z09891462EBSJV2ZBZN8S

INTENDED_ACCOUNT = 979473937812

include $(shell git rev-parse --show-toplevel)/ops/terraform.mk
