export TF_VAR_environment_namespace=prod
export TF_VAR_vpc_cidr_block=10.0.0.0/16
export TF_VAR_private_subnet_count=3

INTENDED_ACCOUNT = 979473937812

include $(shell git rev-parse --show-toplevel)/ops/terraform.mk
