export TF_VAR_environment_namespace=qa
export TF_VAR_vpc_cidr_block=10.0.0.0/16
export TF_VAR_private_subnet_count=2

INTENDED_ACCOUNT = 018002986064

include $(shell git rev-parse --show-toplevel)/ops/terraform.mk
