variable aws_region {
  type        = string
  description = "AWS region to deploy resources to"
  default     = "us-west-2"
}

variable aws_profile {
  type        = string
  description = "Local AWS profile to use for deployments (see ~/.aws/credentials)"
  default     = "nibble-deploy"
}

variable aws_target_account_id {
  type        = string
  description = "The targeted AWS account, used for accessing lambda/db schema buckets"
}

variable environment {
  type        = string
  description = "Name of current deployment environment (e.g. dev, qa, prod)"
}

variable environment_namespace {
  type        = string
  description = "Namespace to use for resources; for qa/prod this is just qa/prod; for dev it should be dev_(username)"
}

variable heroku_sensitive_config_vars {
  type        = map
  description = "Config vars for Heroku; should be autogenerated from SSM"
}
